//try catch and asycn - await || use promises 

module.exports = func => (req, res, next) => 
promises.resolve(func (req, res, next)).catch(next);